// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191023173335_Test102Data")]
    partial class Test102Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 10, 23, 12, 33, 34, 984, DateTimeKind.Local).AddTicks(9555),
                            LastName = "Smith",
                            Name = "Luna"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Wang",
                            Name = "Jackson"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Johnson",
                            Name = "Sara"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Larsson",
                            Name = "Sam"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "June",
                            Name = "Julian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
